[package]
name = "ijimai"
version = "0.0.4"
entrypoint = "ijimai.typ"
authors = ["Alberto Corbi (UNIR)"]
license = "MIT"
description = "Template for writing articles for the International Journal of Interactive Multimedia and Artificial Intelligence (IJIMAI)"
repository = "https://github.com/pammacdotnet/IJIMAI"
categories = ["paper"]

[template]
path = "template"
entrypoint = "paper.typ"
thumbnail = "tests/template/ref/1.png"
